<a href="https://colab.research.google.com/github/vivekreddy00/fmml2021/blob/main/10_Problem_Solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
# Madagascar problem

In [3]:
import numpy as np

In [4]:
A = np.array([[20, 122, 20], [35,180, 35],[50, 220, 65], [70, 300, 30]])
x = np.array([[0.05], [0.002], [0.02]])

In [2]:
# 4x3 . 3x1 = 4x1

In [5]:
y = np.matmul(A,x) - 4.0

In [6]:
Z = np.hstack((A,y))

In [7]:
Z

array([[ 2.000e+01,  1.220e+02,  2.000e+01, -2.356e+00],
       [ 3.500e+01,  1.800e+02,  3.500e+01, -1.190e+00],
       [ 5.000e+01,  2.200e+02,  6.500e+01,  2.400e-01],
       [ 7.000e+01,  3.000e+02,  3.000e+01,  7.000e-01]])

In [9]:
def RankArray(A,x):
  y = np.dot(A,x) - 4.0
  L = np.hstack((A,y))
  return L

In [10]:
print (RankArray(A,x))

[[ 2.000e+01  1.220e+02  2.000e+01 -2.356e+00]
 [ 3.500e+01  1.800e+02  3.500e+01 -1.190e+00]
 [ 5.000e+01  2.200e+02  6.500e+01  2.400e-01]
 [ 7.000e+01  3.000e+02  3.000e+01  7.000e-01]]
